"""add retailer, reference materials, hs code duty rates, box dimensions

Revision ID: 4c4b1fb3294f
Revises: 88a8208ba8fc
Create Date: 2026-07-21 12:54:24.949290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4b1fb3294f'
down_revision: Union[str, Sequence[str], None] = '88a8208ba8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retailers',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_materials',
    sa.Column('design_request_id', sa.Uuid(), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['design_request_id'], ['design_requests.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('design_requests', sa.Column('retailer_id', sa.Uuid(), nullable=True))
    op.add_column('design_requests', sa.Column('requested_deadline', sa.Date(), nullable=True))
    op.add_column('design_requests', sa.Column('requested_colors', sa.ARRAY(sa.String()), nullable=True))
    op.create_foreign_key(
        'design_requests_retailer_id_fkey', 'design_requests', 'retailers', ['retailer_id'], ['id']
    )
    op.add_column('duty_rates', sa.Column('hs_code', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('duty_rates_product_type_id_fkey'), 'duty_rates', type_='foreignkey')
    op.drop_column('duty_rates', 'product_type_id')
    op.add_column('pricing_requests', sa.Column('requested_delivery_date', sa.Date(), nullable=True))
    op.add_column('pricing_requests', sa.Column('requested_quote_validity_until', sa.Date(), nullable=True))
    op.add_column('quote_lines', sa.Column('hs_code', sa.String(length=20), nullable=True))
    op.add_column('quote_lines', sa.Column('box_width_cm', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('quote_lines', sa.Column('box_length_cm', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('quote_lines', sa.Column('box_height_cm', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('quote_lines', sa.Column('box_qty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_lines', 'box_qty')
    op.drop_column('quote_lines', 'box_height_cm')
    op.drop_column('quote_lines', 'box_length_cm')
    op.drop_column('quote_lines', 'box_width_cm')
    op.drop_column('quote_lines', 'hs_code')
    op.drop_column('pricing_requests', 'requested_quote_validity_until')
    op.drop_column('pricing_requests', 'requested_delivery_date')
    op.add_column('duty_rates', sa.Column('product_type_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('duty_rates_product_type_id_fkey'), 'duty_rates', 'product_types', ['product_type_id'], ['id'])
    op.drop_column('duty_rates', 'hs_code')
    op.drop_constraint('design_requests_retailer_id_fkey', 'design_requests', type_='foreignkey')
    op.drop_column('design_requests', 'requested_colors')
    op.drop_column('design_requests', 'requested_deadline')
    op.drop_column('design_requests', 'retailer_id')
    op.drop_table('reference_materials')
    op.drop_table('retailers')
    # ### end Alembic commands ###
