"""initial schema

Revision ID: 88a8208ba8fc
Revises: 
Create Date: 2026-07-20 19:01:52.566945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a8208ba8fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rates',
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rate_to_eur', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_types',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sla_definitions',
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('reminder_frequency', sa.Interval(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'step_name', name='uq_sla_entity_step')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('performed_by', sa.Uuid(), nullable=False),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duty_rates',
    sa.Column('product_type_id', sa.Uuid(), nullable=False),
    sa.Column('destination_location_id', sa.Uuid(), nullable=False),
    sa.Column('rate_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escalation_rules',
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('threshold_after_due', sa.Interval(), nullable=False),
    sa.Column('escalate_to_role', sa.Enum('SALES', 'TRAFFIC_MANAGER', 'LEAD_DESIGNER', 'DTP_DESIGNER', 'COSTING', 'SALES_DIRECTOR', 'ITEM_CREATOR', 'ADMIN', name='role'), nullable=True),
    sa.Column('escalate_to_user_id', sa.Uuid(), nullable=True),
    sa.Column('notify_message_template', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['escalate_to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'step_name', name='uq_escalation_entity_step')
    )
    op.create_table('freight_rates',
    sa.Column('production_location_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_location_id', sa.Uuid(), nullable=False),
    sa.Column('cost_per_cbm', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['production_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('handling_costs',
    sa.Column('product_type_id', sa.Uuid(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='project_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('assigned_to_user_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_to_role', sa.Enum('SALES', 'TRAFFIC_MANAGER', 'LEAD_DESIGNER', 'DTP_DESIGNER', 'COSTING', 'SALES_DIRECTOR', 'ITEM_CREATOR', 'ADMIN', name='role'), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ON_HOLD', 'DONE', name='task_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hold_reason', sa.Text(), nullable=True),
    sa.Column('hold_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remaining_on_hold', sa.Interval(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('SALES', 'TRAFFIC_MANAGER', 'LEAD_DESIGNER', 'DTP_DESIGNER', 'COSTING', 'SALES_DIRECTOR', 'ITEM_CREATOR', 'ADMIN', name='role'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_role')
    )
    op.create_table('escalation_events',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('notified_user_id', sa.Uuid(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['notified_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'IN_APP', name='notification_channel'), nullable=False),
    sa.Column('type', sa.Enum('TASK_ASSIGNED', 'SLA_REMINDER', 'ESCALATION', 'REJECTED', 'APPROVED', name='notification_type'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_ITEM_CREATION', 'READY', name='order_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('DESIGN', 'PRICING', name='request_category'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subtype', sa.Enum('PRESENTATION', 'TEMPLATE', 'MOCKUP', name='design_request_subtype'), nullable=False),
    sa.Column('product_type_id', sa.Uuid(), nullable=True),
    sa.Column('design_project_number', sa.String(length=50), nullable=True),
    sa.Column('lead_designer_id', sa.Uuid(), nullable=True),
    sa.Column('dtp_designer_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'TRIAGED', 'IN_PROGRESS', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='design_request_status'), nullable=False),
    sa.Column('leading_pricing_request_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['dtp_designer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['lead_designer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_creation_requests',
    sa.Column('design_request_id', sa.Uuid(), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('size', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DONE', name='item_creation_status'), nullable=False),
    sa.Column('assigned_item_creator_id', sa.Uuid(), nullable=True),
    sa.Column('erp_item_number', sa.String(length=100), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_item_creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['design_request_id'], ['design_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_versions',
    sa.Column('design_request_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('pdf_url', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'FINAL_READY', name='template_version_status'), nullable=False),
    sa.Column('trigger_reason', sa.Enum('INITIAL', 'CUSTOMER_CHANGE', 'MISTAKE_FIX', name='template_version_trigger'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['design_request_id'], ['design_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('TEMPLATE', 'QUESTIONS', name='pricing_request_source_type'), nullable=False),
    sa.Column('template_version_id', sa.Uuid(), nullable=True),
    sa.Column('product_type_id', sa.Uuid(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('assigned_costing_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETE', name='pricing_request_status'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_costing_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ),
    sa.ForeignKeyConstraint(['template_version_id'], ['template_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_lines',
    sa.Column('pricing_request_id', sa.Uuid(), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('size', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('production_location_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_location_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'PRICED', name='quote_line_status'), nullable=False),
    sa.Column('factory_id', sa.Uuid(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('purchase_currency', sa.String(length=3), nullable=True),
    sa.Column('fx_rate_to_eur', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('volume_cbm', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('freight_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('duty_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('handling_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('landed_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('margin_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('sell_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['pricing_request_id'], ['pricing_requests.id'], ),
    sa.ForeignKeyConstraint(['production_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factory_quote_options',
    sa.Column('quote_line_id', sa.Uuid(), nullable=False),
    sa.Column('factory_id', sa.Uuid(), nullable=False),
    sa.Column('quoted_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['quote_line_id'], ['quote_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_lines',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('quote_line_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('item_creation_request_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_creation_request_id'], ['item_creation_requests.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['quote_line_id'], ['quote_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Deferred: breaks the design_requests -> pricing_requests ->
    # template_versions -> design_requests table-creation cycle.
    op.create_foreign_key(
        'fk_design_requests_leading_pricing_request_id',
        'design_requests', 'pricing_requests',
        ['leading_pricing_request_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_design_requests_leading_pricing_request_id',
        'design_requests', type_='foreignkey',
    )
    op.drop_table('order_lines')
    op.drop_table('factory_quote_options')
    op.drop_table('quote_lines')
    op.drop_table('pricing_requests')
    op.drop_table('template_versions')
    op.drop_table('item_creation_requests')
    op.drop_table('design_requests')
    op.drop_table('requests')
    op.drop_table('orders')
    op.drop_table('notifications')
    op.drop_table('escalation_events')
    op.drop_table('user_roles')
    op.drop_table('tasks')
    op.drop_table('projects')
    op.drop_table('handling_costs')
    op.drop_table('freight_rates')
    op.drop_table('escalation_rules')
    op.drop_table('duty_rates')
    op.drop_table('comments')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sla_definitions')
    op.drop_table('product_types')
    op.drop_table('locations')
    op.drop_table('factories')
    op.drop_table('exchange_rates')
    op.drop_table('customers')
    # ### end Alembic commands ###

    # op.drop_table() does not drop the Postgres ENUM types backing our
    # Enum columns, so without this every one of them would be left behind
    # (and re-running upgrade() from scratch would fail with "type already
    # exists"). Dropped explicitly, in no particular order, after every
    # table that references them is already gone.
    for enum_name in (
        "role",
        "project_status",
        "request_category",
        "design_request_subtype",
        "design_request_status",
        "template_version_status",
        "template_version_trigger",
        "pricing_request_source_type",
        "pricing_request_status",
        "quote_line_status",
        "order_status",
        "item_creation_status",
        "task_status",
        "notification_channel",
        "notification_type",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
